site_name: Lan Group Wiki (SCNU)
site_url: https://yifei-zhu.github.io/LanGroupWiki/
repo_name: LanGroupWiki
repo_url: https://github.com/Yifei-Zhu/LanGroupWiki.git
extra:
  social:
#     - icon: material/web
#       link: xxxxx
#       name: 课题组网站
#     - icon: fontawesome/brands/github
#       link: https://github.com/chenggroup
#       name: 课题组Github
    - icon: fontawesome/solid/paper-plane
      link: mailto:zhenggang.lan@m.scnu.edu.cn
      name: 联系兰峥岗老师
    # - icon: fontawesome/solid/plane-departure
    - icon: fontawesome/solid/gear
      link: mailto:zhuyifei.phil@gmail.com
      name: 联系Wiki运营
  # consent:
  #   title: Cookie consent
  #   description: >-
  #     We use cookies to recognize your repeated visits and preferences, as well
  #     as to measure the effectiveness of our documentation and whether users
  #     find what they're searching for. With your consent, you're helping us to
  #     make our documentation better.
  # version:
  #   provider: mike
  generator: false

theme:
  name: material
  custom_dir: overrides
  icon:
    repo: fontawesome/brands/github
  palette:
    - scheme: default
      primary: indigo
      accent: blue
      toggle:
        icon: material/brightness-7
        # name: Switch to dark mode
        name: 切换至深色模式

    - scheme: slate
      primary: indigo
      accent: teal
      toggle:
        icon: material/brightness-4
        # name: Switch to light mode
        name: 切换至浅色模式

  language: zh
  features:
    - header.autohide
    - navigation.instant
    # - navigation.tabs
    # - navigation.tabs.sticky
    - navigation.path
    - navigation.sections
    - navigation.expand
    - navigation.indexes
    - navigation.top
    - content.tooltips
    - search.suggest
    # - search.highlight
    - search.share
    - content.code.annotate
    # - toc.integrate

    #  render temporary announcements that can be marked as read by the user
    - announce.dismiss



plugins:
  - offline
  - search:
      separator: '[\s\-\.]'
  - tags:
      tags_file: wiki/tags.md

markdown_extensions:
  # Python Markdown
  - abbr
  - admonition
  - attr_list
  - def_list
  - footnotes
  - md_in_html
  - toc:
      permalink: true
  - markdown.extensions.codehilite

  # Python Markdown Extensions
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.highlight
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.snippets
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde

extra_javascript:
  - javascripts/analytic.js
  - javascripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js

nav:
  - Home: index.md
  - Wikis:
      - 作者须知:
        - wiki/Authors/author_note.md
        - wiki/Authors/markdown.md
        - wiki/Authors/submit_wiki.md

      - 新生入门:
        - 导览: wiki/Beginners/welcome.md

      - 软件使用:
        - ./wiki/Software_guide/test.md

      - 代码分享:
        - ./wiki/Codes/lujz_internal_coordinate.md

      - 资料推荐:
        - ./wiki/Recommend/books.md

      - Tags 快速索引: wiki/tags.md

      - 资源下载: downloads/download_list.md

